name: "CI"
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        env:
          - server
          - client
        modpack:
          - cyclops-all
          - cyclops-all-deps
          - cyclops-id
        mc:
          - 1.21.1
          - 1.21.11
        loader:
          - neoforge
          - forge
          - fabric
        include:
          - mc: 1.21.1
            loader: fabric
            fabric-api: 0.116.7 # https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/all?page=1&pageSize=20&showAlphaFiles=show
            fabric-gametest-api: 2.0.9+50ed0faf7a # https://maven.fabricmc.net/net/fabricmc/fabric-api/fabric-gametest-api-v1/
          - mc: 1.21.11
            loader: fabric
            fabric-api: 0.141.1 # https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/all?page=1&pageSize=20&showAlphaFiles=show
            fabric-gametest-api: 3.1.9+39ce47f5f3 # https://maven.fabricmc.net/net/fabricmc/fabric-api/fabric-gametest-api-v1/
        exclude:
          - modpack: cyclops-id # ID does not exist for Forge
            loader: forge
          - modpack: cyclops-id # ID does not exist for Fabric
            loader: fabric
          - modpack: cyclops-all-deps # No deps are relevant for Forge mods
            loader: forge
          - modpack: cyclops-all-deps # No deps are relevant for Fabric mods
            loader: fabric
          - modpack: cyclops-all-deps # Mod compats have not been added for 1.21.11 yet
            mc: 1.21.11
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v6
        with:
          submodules: true
      - name: 'Setup Java'
        uses: actions/setup-java@v5
        with:
          distribution: 'microsoft'
          java-version: 21
      - name: 'Fetch modpack'
        uses: nick-fields/retry@v3 # Retry, as some maven repos can be finicky
        with:
          timeout_minutes: 5
          max_attempts: 3
          command: ./fetch.sh modpacks/${{ matrix.modpack }}/${{ matrix.mc }}/${{ matrix.loader }}/pom.xml $(pwd)/run/mods
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Test in runtime client'
        if: matrix.env == 'client' && (matrix.loader != 'forge' && matrix.loader != 'fabric' && matrix.mc != '1.21.11') # This does not work yet on Forge, Fabric, or 1.21.11 (all loaders)
        timeout-minutes: 10
        uses: headlesshq/mc-runtime-test@4.1.0
        with:
          mc: ${{ matrix.mc }}
          modloader: ${{ matrix.loader }}
          regex: .*${{ matrix.loader }}.*
          mc-runtime-test: ${{ matrix.loader == 'forge' && 'lexforge' || matrix.loader }}
          java: ${{ env.java_version }}
          headlessmc-command: --jvm "-Djava.awt.headless=true -DMcRuntimeGameTestMinExpectedGameTests=1 -Dneoforge.enabledGameTestNamespaces=cyclopscore,commoncapabilities"
          fabric-api: ${{ matrix.fabric-api || 'none' }}
          fabric-gametest-api: ${{ matrix.fabric-gametest-api || 'none' }}
      - name: 'Test in runtime server'
        if: matrix.env == 'server'
        timeout-minutes: 10
        uses: headlesshq/mc-server-test@1.1.1
        with:
          java: ${{ env.java_version }}
          mc: ${{ matrix.mc }}
          modloader: ${{ matrix.loader }}
          fabric-api: ${{ matrix.fabric-api || 'none' }}
      - uses: actions/upload-artifact@v6
        if: matrix.env == 'client'
        with:
          name: ${{ matrix.modpack }}-${{ matrix.mc }}-${{ matrix.loader }}-mods
          path: run/mods
