name: "CI"
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        mc:
          - 1.21.1
        loader:
          - neoforge
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: 'Setup Java'
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: 21
      - name: 'Fetch modpack'
        run: ./fetch.sh modpacks/cyclops-all/${{ matrix.mc }}/${{ matrix.loader }}/pom.xml
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Test in runtime client'
        uses: headlesshq/mc-runtime-test@4.1.0
        with:
          mc: ${{ matrix.mc }}
          modloader: ${{ matrix.loader }}
          regex: .*${{ matrix.loader }}.*
          mc-runtime-test: ${{ matrix.loader }}
          java: ${{ env.java_version }}
          headlessmc-command: --jvm "-Djava.awt.headless=true -DMcRuntimeGameTestMinExpectedGameTests=1"
