name: "CI"
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        modpack:
          - cyclops-all
        mc:
          - 1.21.1
        loader:
          - neoforge
          - forge
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v6
        with:
          submodules: true
      - name: 'Setup Java'
        uses: actions/setup-java@v5
        with:
          distribution: 'microsoft'
          java-version: 21
      - name: 'Fetch modpack'
        run: ./fetch.sh modpacks/${{ matrix.modpack }}/${{ matrix.mc }}/${{ matrix.loader }}/pom.xml $(pwd)/run/mods
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Test in runtime client'
        uses: headlesshq/mc-runtime-test@4.1.0
        with:
          mc: ${{ matrix.mc }}
          modloader: ${{ matrix.loader }}
          regex: .*${{ matrix.loader }}.*
          mc-runtime-test: ${{ matrix.loader == 'forge' && 'lexforge' || matrix.loader }}
          java: ${{ env.java_version }}
          headlessmc-command: --jvm "-Djava.awt.headless=true -DMcRuntimeGameTestMinExpectedGameTests=1 -Dneoforge.enabledGameTestNamespaces=cyclopscore,commoncapabilities"
      - uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.modpack }}-${{ matrix.mc }}-${{ matrix.loader }}-mods
          path: run/mods
